### ISSUE TITLE
Seeking Pcap4J performance tips

### ISSUE THREAD

**Issue by bayweiheng** [kaitoy/pcap4j#115]
Hi kaitoy,

First let me just thank you for making this wrapper library available for us to use, and continuing to maintain it over the years.

I recently tried switching from JNetPcap to Pcap4J for some packet capture application, due to Pcap4J still being maintained (JNetpcap stopped development in 2013). JNetPcap uses this nextBuffer function inside its ByteBufferHandler, which is akin to Pcap4J's gotPacket inside its RawPacketListener. I stuff the buffers received onto a (synchronous) queue and other threads take from that queue and send the data to a Kafka server using a Producer (so far no BufferUnderflowException thanks to the Sync queue). I did the same thing for Pcap4J, stuffing the byte array instead, and Producer accordingly.

However, perhaps because JNetPcap performs the nextBuffer action directly in kernel and Pcap4J extracts the data out into a byte array first (not sure about the implementation). Pcap4J cannot manage the previous throughput achieved with JNetPcap (2Gbps with 0.02% packet loss became >90% loss at the same speed).

Am I using the wrong API, and are there tips you could suggest to close the gap between my two applications? Thank you!

**Comment by kaitoy** [comment]
What are you doing in your RawPacketListener implementation?
You should make the implementation as light as possible or divide it from the thread that takes packets from the ring buffer by using `loop(int packetCount, RawPacketListener listener, Executor executor)` (instead of  `loop(int packetCount, RawPacketListener listener)`).

**Comment by eternal-echoes** [comment]
I am just putting it on a synchronous queue (one line - queue.put(packet)), and I have tried both using self-created executors and creating my own fixed number of threads, but nothing seems to give me the previous performance. Is it because data is copied out into an array first, instead of operations being performed at the buffer level where the packet is captured?

**Comment by kaitoy** [comment]
You can change the buffer size by creating a PcapHandle instance using its Builder API.
Please refer to [org.pcap4j.sample.GetNextPacket](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-sample/src/main/java/org/pcap4j/sample/GetNextPacket.java)

Anyway, I will check the source of JNetPcap's ByteBufferHandler to find idea for better performance.

**Comment by bayweiheng** [comment]
yes, I tried with both 2MiB (if I'm not wrong that is libpcap default for Linux) and 128 MiB and there was no significant performance gain. I am not sure whether buffer size would help since the issue is the handler function being not fast enough per packet (thus driver drops a lot). Testing was done with TCPReplay, so was at a constant speed.

**Comment by kaitoy** [comment]
Pcap.loop of JNetPcap is a native method. It's the reason for the better performance.
Generally, the more threads the Executor can handle and the more the buffer size is, the less packets PcapHandle losses.

Pcap4J can read packets from a pcap file. So, you may be better to capture packets and generate a pcap file by another tool, and read it by Pcap4J.
