### ISSUE TITLE
NullPointerException When Parsing Some Transport Layer Headers

### ISSUE THREAD

**Issue by zzenonn** [kaitoy/pcap4j#126]
Hello, @kaitoy . 

Excellent library, however, I am having problems parsing some TCP and UDP headers in raw IP packets.

This is the code I used, and I am sure that it is a UDP packet.
```java
UdpPacket udpPacket = packet.get(UdpPacket.class);

srcPort = udpPacket.getHeader().getSrcPort().valueAsInt();

dstPort = udpPacket.getHeader().getDstPort().valueAsInt()
```
The raw bytes using `packet.getRawData()` return the sequence `45 00 00 39 87 0A 00 B9 37 11 D3 74 6D 61 43 47 5C 1B 1B B9`, but on Wireshark, the full hexdump of that packet is 
```
0000   45 00 05 dc 87 0a 20 00 37 11 ae 8a 6d 61 43 47

0010   5c 1b 1b b9 8f 8c 1f 90 05 ed 64 c3
```
with `8f 8c 1f 90 05 ed 64 c3`  as the UDP Header. This happens for several other packets as well.

**Comment by kaitoy** [comment]
Thank you for reporting the issue.
I will take a look at it.

**Comment by zzenonn** [comment]
Thank you. This is the PCAP file I was parsing.
[splits.pcap.zip](https://github.com/kaitoy/pcap4j/files/1400670/splits.pcap.zip)

**Comment by kaitoy** [comment]
`45 00 00 39 87 0A 00 B9 37 11 D3 74 6D 61 43 47 5C 1B 1B B9` is a fragmented IP packet. Pcap4J create a FragmentedPacket object instead of UdpPacket for such a packet.
So, `packet.get(UdpPacket.class)` returned null and `udpPacket.getHeader()` threw NPE.
You need to reassemble IP packets, as Wireshark does internally.
Please refer to [this sample ](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-sample/src/main/java/org/pcap4j/sample/SendFragmentedEcho.java) that is doing IP packet reassembly.
