### ISSUE TITLE
Does pcap4j support PPPoE?

### ISSUE THREAD

**Issue by Oryteclin** [kaitoy/pcap4j#213]
I'm trying to use lag checker
[MakeLobbiesGreatAgain](https://github.com/PsiLupan/MakeLobbiesGreatAgain)
The problem is that It doesn't show my PPPoE connection (WAN Miniport), only the phisical device with different IP.
I'd like to know is it a restriction of pcap4j?
Basically MLGA use method Pcaps#findAllDevs, which show only 1 device, but doesn't show connection PPPoE.

**Comment by ohuseyinoglu** [comment]
I was curious about MLGA and quickly checked the readme. There's a [portion like this](https://github.com/PsiLupan/MakeLobbiesGreatAgain#how-to-install-and-use) in there:

> If UAC is enabled: You may need to run the application via Command Prompt (this is due to the **PCap4J library being unable to find devices**).
> <and then explains how to run the program/jar as an administrator>

Was this how you were running on your computer? If not, give that a try.

Other than that, Kaitoy may have other suggestions as the original author, but, as a standard test, I also would recommend running Wireshark on the machine (again "as administrator" just in case!). If Wireshark can see the PPPoE network interface, pcap4j should also be able to see it, since they both utilize the underlying pcap/npcap libraries.

**Comment by Oryteclin** [comment]
I know how to launch the application. It works fine via Wi-Fi adapter, but I need to use it via wired connection.

**Comment by kaitoy** [comment]
`Pcaps#findAllDevs` might unable to find PPPoE devices due to a bug, I'm not sure, though.
Any errors when you run Pcap4J to find the PPPoE device?

**Comment by kaitoy** [comment]
Even If `Pcaps#findAllDevs` can't find the device, you still can start capture packets on it by 'PcapHandle.Builder'.

**Comment by kaitoy** [comment]
Close this for inactivity.
