### ISSUE TITLE
JNA error handling callback exception continuing

### ISSUE THREAD

**Issue by postol** [kaitoy/pcap4j#36]
Hi,

firstly I would like to thank you for a very nice library. We are using it to capture packets in our application and we are experiencing the following issue:

We create a handle with openLive call and start a loop on it with handle.loop(-1, listener); and we randomly start seeing the JNA errors printed in console, concretely JNA error handling callback exception continuing and the capturing stops working completely afterwards. Unfortunately it is not deterministic and happens only sometime and randomly.

Environment we use:
Java:      1.7.0_75
OS:         W2k3 SE SP2, 32 bit
WinPcap:    4.1.3

It would really help us if you can provide any help with this issue.

Thank you and kind regards,

Petr

**Comment by kaitoy** [comment]
Thank you for using Pcap4J. It's my pleasure.

I investigated the error and found it occurs when the callback (i.e. listener) throws an exception and the callback exception handler throws an exception.
It looks the default callback exception handler doesn't throw any exceptions. Did you change the handler?
Anyway, please try https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.4.1-SNAPSHOT/pcap4j-distribution-1.4.1-20150422.050608-3-bin.zip.
This is with a fix to catch exceptions thrown by callback before the handler and write error logs.
I expect you will see error logs describing exceptions instead of "JNA: error handling callback exception, continuing".

**Comment by postol** [comment]
Thanks for quick reply ... we will try this new version and hopefully we will see what is causing the issue now. And to answer your question - we didn't change the handler at all.
