### ISSUE TITLE
util.ByteArrays.toHexString() performance slow compared to DatatypeConverter.printHexBinary()

### ISSUE THREAD

**Issue by strikaco** [kaitoy/pcap4j#50]
Hello,

Have you considered using the native javax.xml.bind.DatatypeConverter.printHexBinary() instead of the util.ByteArrays.toHexString function? In my implementation of pcap4j (which is admittedly a very specific use case) I've noticed speeds orders of magnitudes faster by replacing calls to toHexString with DatatypeConverter.printHexBinary.

Thanks for this excellent project!

**Comment by kaitoy** [comment]
Thank you for using Pcap4J.

There are two problems to use DatatypeConverter.printHexBinary.
One is that Android doesn't support it, and the other one is that we cannot specify a separator.
Anyway, I learned current ByteArrays.toHexString implementation is very slow mainly because of use of String.format. I will improve it.

**Comment by strikaco** [comment]
Makes sense about Android, I don't do Android programming so I wouldn't have thought of that.

ありがとうございます！

**Comment by kaitoy** [comment]
I made [changes](https://github.com/kaitoy/pcap4j/commit/2bf4f56bd24c94d20c81f2e1976a8fa601427711) for the performance improvement.
The new ByteArrays.toHexString is 1100 times faster than old one and 15 times faster than DatatypeConverter.printHexBinary with byte[10000].
