### ISSUE TITLE
JVM crash - SIGSEV

### ISSUE THREAD

**Issue by postol** [kaitoy/pcap4j#64]
Hi,

we are using your pcap4j for network sniffing (btw thanks a lot for your hard work) and we are seeing frequent crashes after we upgraded to 1.6.2 version. Before we were using version 1.3.0 and the crash was not happening. The other change we did with version upgrade is that we kept only static packet factory in gradle script, before we had both properties based factory and static factory included. No other significant changes.

The issue is in: C  [jna7435779821996815317.tmp+0xa32b]  Java_com_sun_jna_Native_setInt+0x9b

Please see the attached error log below.

Any help will be much appreciated.

Thank you.
Petr

[hs_err_pid1927.txt](https://github.com/kaitoy/pcap4j/files/331389/hs_err_pid1927.txt)

**Comment by kaitoy** [comment]
Thank you for using Pcap4J and reporting the issue.
I investigated your log and made a fix. Please try [this](https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.6.5-SNAPSHOT/pcap4j-distribution-1.6.5-20160624.183926-6-bin.zip).

**Comment by jiri-dev** [comment]
Hi kaitoy,

I work with Petr who reported the issue and tried out your fix. The issue still persists. However, I think the issue is in the way we use your library or may be in the design of the API. I found the reason why our app was crashing. On our side we do:

`private final PcapHandle handle = ...;`
`...`
`BpfProgram filter = handle.compileFilter(expression, BpfCompileMode.OPTIMIZE, mask);`
`handle.setFilter(filter);`

When we create the 'filter' we set it on the PcapHandle instance but the 'filter' is just a local variable which is collected at some point by GC and its finalizer gets called and causes to release native memory holding the code of the filter which is, however, used within the pcap capture logic hence the app crashes, as the capture logic is still using the filter.

For now, we keep instance of the BpfProgram as a class variable so that it doesn't get collected and this resolved the issue.

However, can I suggest that the PcapHandle.setFilter() method keeps the instance so that the issue is completely hidden for the pcap4j user?

Thank you,
Jiri

**Comment by kaitoy** [comment]
I think it wouldn't be a problem if a bpf program will be freed after it's set to a pcap handle. As far as I see the source code of libpcap, the bpf program's data is memcopied into the pcap handle's memory and the pcap handle won't refer to the bpf program's memory during capturing packets.
Actually, in `PcapHandle.setFilter(String, BpfCompileMode, Inet4Address)`, [the bpf program is freed just after it's set to the handle.](https://github.com/kaitoy/pcap4j/blob/v1/pcap4j-core/src/main/java/org/pcap4j/core/PcapHandle.java#L507) but I've never seen any problems around it.
It seemed to me JNA's autoWrite did something wrong according to hs_err_pid1927.txt. So, my fix was intended to disable the autoWrite on bpf programs. But now I found it was incomplete.
I improved my fix. Please try [this](https://oss.sonatype.org/content/repositories/snapshots/org/pcap4j/pcap4j-distribution/1.6.5-SNAPSHOT/pcap4j-distribution-1.6.5-20160701.220733-7-bin.zip)
