### ISSUE TITLE
Replace boilerplate with lombok

### ISSUE THREAD

**Issue by yiftachbeer** [kaitoy/pcap4j#69]
Much of the code in the various Packet/Header/Builder objects could be reduced by using lombok ([@Builder](https://projectlombok.org/features/Builder.html), [@Value](https://projectlombok.org/features/Value.html), [@Data](https://projectlombok.org/features/Data.html)).

Thoughts?

**Comment by jeffreymyers** [comment]
Wouldn't that add a transitive runtime dependency?

**Comment by kaitoy** [comment]
@yiftachbeer 
I've been thinking about using lombok. I'm just hesitating to learn new things...

@jeffreymyers
I'm not very sure but I guess using lombok wouldn't add any runtime dependencies.
Anyway I need more investigation.

**Comment by yiftachbeer** [comment]
As long as `<scope>provided</scope>` is given in the pom.xml, the dependency should not be transitive.

**Comment by jeffreymyers** [comment]
Oh! So once the bytecode manipulation is done at compile-time, there's no runtime library requirement? I missed that aspect when I encountered its usage in the past.

**Comment by kaitoy** [comment]
I learned Lombok and found it's not really good tool for Pcap4J.

`@Builder` doesn't do good job for packet classes. Builders generated by the annotation can't extend or implement other classes, their names don't match for Pcap4J API, javadoc comments are not generated for them, and custom constructors can't be added to them.

Almost all classes in Pcap4j other than builders are immutable, so `@Data` and `@Setter` are not useful.

I don't like how to add javadoc comments to getters using `@Getter` because it's not beautiful. And `@Getter` doesn't support defensive copy. This is a critical flaw. IDE generates getters, which is enough for me.

`@EqualsAndHashCode` is not bad. But again IDE generates the same, which is enough.

`@Value` doesn't generate code I want.

Only `val` and `@NonNull` look useful. I think I will not find so many chances to use `@NonNull` when writing packet classes, though.

I'll hold off on introducing Lombok for a while.
