### ISSUE TITLE
How to extract http header 

### ISSUE THREAD

**Issue by vinodatphp** [kaitoy/pcap4j#85]
How do I extract http data from captured packets

**Comment by kaitoy** [comment]
You can get a TCP packet from the captured packet by `TcpPacket tcpPacket = capturedPacket.get(TcpPacket.class);`.
The TCP packet's payload is a piece of an HTTP packet.
To get a whole HTTP packet, collect all TCP packets in a TCP session, sort them by their sequence numbers, and merge their payloads. (Please refer to a [sample](https://gist.github.com/kaitoy/2aca1d6b8644fcccf0cfa5d30f5fe573).)
Here, you can get just a byte array. You need to dissect it in your way to see desired information in it (Pcap4J doesn't support HTTP packet yet).
Because HTTP is a text protocol, probably you can just convert it to String and print (i.e. `System.out.println(new String(theByteArray, "UTF-8"));`).

**Comment by kaitoy** [comment]
By the way, I will implement TCP reassembly feature in Pcap4J 2.

**Comment by PhamTrinh6677** [comment]
I read "  Practical Data Hiding in TCP/IP " of you.
I have one question ,
What application or tool might you have in hiding information in TCP/IP Header ?
I'm sorry , because my english is not good.
Thanks you , good luck

**Comment by kaitoy** [comment]
@PhamTrinh6677 
Sorry but I have no idea on data hiding in TCP/IP.

**Comment by PhamTrinh6677** [comment]
Ok , thanks you , good night and good luck

2018-06-04 21:03 GMT+07:00 Kaito Yamada <notifications@github.com>:

**Comment by koolmano** [comment]
Hi, Kaitoy-san, veery good job you've done. But there is a problem running your examples.
You see, I'm debugging it in Netbeans but netbeans running your examples in user mode.
Your project need to enter super user root privileges. Do you know how to run your samples in root mode in Netbeans? Thank you very much.

**Comment by PhamTrinh6677** [comment]
Ok  , Thanks you for helping of you , I understand .

2018-06-26 0:20 GMT+07:00 koolmano <notifications@github.com>:

**Comment by kaitoy** [comment]
@koolmano 
I think you need to add capabilities.
Please refer to [here](https://github.com/kaitoy/pcap4j#others)

**Comment by s5r3** [comment]
> By the way, I will implement TCP reassembly feature in Pcap4J 2.

Hi @kaitoy, is there any update on this, or no plan at this moment?

Regardless of that, many thanks for your awesome library.
